"""Block 7. Callbacks: logging, guardrails, filters.

Demonstrates 4 callbacks on a single agent:
  - before_agent_callback  — logs agent entry
  - before_model_callback  — guardrail (blocks by keywords)
  - before_tool_callback   — normalizes tool arguments
  - after_model_callback   — appends a signature to the response

Run:
    cd checkpoints/07_callbacks
    adk web
"""

import os

# Model name is read from ADK_MODEL (see .env / .env.example).
# Falls back to gemini-3.1-flash-lite — the most generous free-tier RPD (500/day).
MODEL = os.getenv("ADK_MODEL", "gemini-3.1-flash-lite")

from typing import Any, Dict, Optional

from google.adk.agents import LlmAgent
from google.adk.agents.callback_context import CallbackContext
from google.adk.models import LlmRequest, LlmResponse
from google.adk.tools.base_tool import BaseTool
from google.adk.tools.tool_context import ToolContext
from google.genai import types


# --- Tool ---

def get_weather(city: str) -> dict:
    """Returns the current weather in the specified city.

    Args:
        city: City name in English.
    """
    fake_data = {
        "new york": "It's sunny in New York, 25°C.",
        "london": "It's cloudy in London, 14°C.",
        "tashkent": "It's clear in Tashkent, 28°C.",
    }
    report = fake_data.get(city.lower())
    if report:
        return {"status": "success", "report": report}
    return {"status": "error", "error_message": f"No data for {city}."}


# --- Callback 1: log agent entry ---

def log_entry(callback_context: CallbackContext) -> Optional[types.Content]:
    """Just logs — returns None so the agent runs as usual."""
    print(
        f"[LOG] enter agent={callback_context.agent_name} "
        f"inv={callback_context.invocation_id}"
    )
    return None


# --- Callback 2: input guardrail (before_model_callback) ---

BLOCKED_WORDS = ("api_key", "password", "secret", "token")


def block_secrets(
    callback_context: CallbackContext, llm_request: LlmRequest
) -> Optional[LlmResponse]:
    """If the latest user message contains blocked words —
    substitute the response and skip the LLM call."""
    last_text = ""
    if llm_request.contents:
        last = llm_request.contents[-1]
        if last.parts:
            last_text = (last.parts[0].text or "").lower()

    if any(word in last_text for word in BLOCKED_WORDS):
        print(f"[GUARDRAIL] blocked: '{last_text[:50]}...'")
        return LlmResponse(
            content=types.Content(
                role="model",
                parts=[
                    types.Part(
                        text="I don't discuss secrets. "
                        "Please rephrase your question."
                    )
                ],
            )
        )
    return None  # proceed as usual


# --- Callback 3: tool argument normalization ---

def normalize_city(
    tool: BaseTool, args: Dict[str, Any], tool_context: ToolContext
) -> Optional[Dict]:
    """Normalizes args['city'] in place before the tool is called."""
    if tool.name == "get_weather" and "city" in args:
        original = args["city"]
        args["city"] = original.strip().title()
        if original != args["city"]:
            print(f"[Callback] normalized city '{original}' -> '{args['city']}'")
    return None


# --- Callback 4: post-process the model response ---

SIGNATURE = "\n\n— Generated by an ADK agent"


def append_signature(
    callback_context: CallbackContext, llm_response: LlmResponse
) -> Optional[LlmResponse]:
    """Appends a signature to the final text response."""
    if not llm_response.content or not llm_response.content.parts:
        return None
    original = llm_response.content.parts[0].text or ""
    if not original:
        return None
    return LlmResponse(
        content=types.Content(
            role="model",
            parts=[types.Part(text=original + SIGNATURE)],
        )
    )


# --- Agent with all callbacks wired up ---

root_agent = LlmAgent(
    name="guarded_weather_agent",
    model=MODEL,
    description="Agent with logging, guardrail, and post-processing.",
    instruction=(
        "You are a helpful assistant. Answer weather questions "
        "using the get_weather tool."
    ),
    tools=[get_weather],
    before_agent_callback=log_entry,
    before_model_callback=block_secrets,
    before_tool_callback=normalize_city,
    after_model_callback=append_signature,
)
