"""Block 10. Final: everything together.

Final agent version combining everything from the workshop:
  - tools: weather, time, memory
  - callbacks: logging, guardrail, normalization, signature
  - streaming-ready (via RunConfig in any runner)
  - evaluation-ready (tests/ alongside)

Run:
    cd checkpoints/10_final
    adk web
"""

import os

# Model name is read from ADK_MODEL (see .env / .env.example).
# Falls back to gemini-3.1-flash-lite — the most generous free-tier RPD (500/day).
MODEL = os.getenv("ADK_MODEL", "gemini-3.1-flash-lite")

import datetime
from typing import Any, Dict, Optional
from zoneinfo import ZoneInfo

from google.adk.agents import LlmAgent
from google.adk.agents.callback_context import CallbackContext
from google.adk.models import LlmRequest, LlmResponse
from google.adk.tools.base_tool import BaseTool
from google.adk.tools.tool_context import ToolContext
from google.genai import types


# === TOOLS ===

def get_weather(city: str) -> dict:
    """Returns the current weather in the specified city.

    Args:
        city: City name in English.
    """
    fake_data = {
        "new york": "It's sunny in New York, 25°C.",
        "london": "It's cloudy in London, 14°C.",
        "tashkent": "It's clear in Tashkent, 28°C.",
    }
    report = fake_data.get(city.lower())
    if report:
        return {"status": "success", "report": report}
    return {"status": "error", "error_message": f"No data for {city}."}


def get_current_time(city: str) -> dict:
    """Returns the current time in the specified city.

    Args:
        city: City name in English.
    """
    tz_map = {
        "new york": "America/New_York",
        "london": "Europe/London",
        "tashkent": "Asia/Tashkent",
    }
    tz_id = tz_map.get(city.lower())
    if not tz_id:
        return {"status": "error", "error_message": f"No timezone for {city}."}
    now = datetime.datetime.now(ZoneInfo(tz_id))
    return {"status": "success", "report": now.strftime("%Y-%m-%d %H:%M:%S %Z")}


def remember_preference(key: str, value: str, tool_context: ToolContext) -> dict:
    """Saves a user preference to session state.

    Args:
        key: Key (e.g., "favorite_city").
        value: Value.
        tool_context: Session context (passed by ADK automatically).
    """
    tool_context.state[key] = value
    return {"status": "success", "saved": {key: value}}


def recall_preference(key: str, tool_context: ToolContext) -> dict:
    """Retrieves a saved preference.

    Args:
        key: Key to look up.
        tool_context: Session context (passed by ADK automatically).
    """
    value = tool_context.state.get(key)
    if value is None:
        return {"status": "error", "error_message": f"No value for {key}."}
    return {"status": "success", "value": value}


# === CALLBACKS ===

BLOCKED_WORDS = ("api_key", "password", "secret", "token")
SIGNATURE = "\n\n— Generated by an ADK agent"


def log_entry(callback_context: CallbackContext) -> Optional[types.Content]:
    print(
        f"[LOG] enter agent={callback_context.agent_name} "
        f"inv={callback_context.invocation_id}"
    )
    return None


def block_secrets(
    callback_context: CallbackContext, llm_request: LlmRequest
) -> Optional[LlmResponse]:
    last_text = ""
    if llm_request.contents:
        last = llm_request.contents[-1]
        if last.parts:
            last_text = (last.parts[0].text or "").lower()
    if any(word in last_text for word in BLOCKED_WORDS):
        return LlmResponse(
            content=types.Content(
                role="model",
                parts=[types.Part(text="I don't discuss secrets.")],
            )
        )
    return None


def normalize_city(
    tool: BaseTool, args: Dict[str, Any], tool_context: ToolContext
) -> Optional[Dict]:
    if tool.name in ("get_weather", "get_current_time") and "city" in args:
        args["city"] = args["city"].strip().title()
    return None


def append_signature(
    callback_context: CallbackContext, llm_response: LlmResponse
) -> Optional[LlmResponse]:
    if not llm_response.content or not llm_response.content.parts:
        return None
    original = llm_response.content.parts[0].text or ""
    if not original:
        return None
    return LlmResponse(
        content=types.Content(
            role="model",
            parts=[types.Part(text=original + SIGNATURE)],
        )
    )


# === AGENT ===

root_agent = LlmAgent(
    name="final_weather_agent",
    model=MODEL,
    description="Final workshop agent: tools + memory + callbacks.",
    instruction=(
        "You are a helpful assistant. Tools:\n"
        "- get_weather / get_current_time — weather and time;\n"
        "- remember_preference — remember user preferences "
        "(e.g., favorite city);\n"
        "- recall_preference — retrieve saved data.\n"
        "If you know the user's favorite city — use it by default."
    ),
    tools=[get_weather, get_current_time, remember_preference, recall_preference],
    before_agent_callback=log_entry,
    before_model_callback=block_secrets,
    before_tool_callback=normalize_city,
    after_model_callback=append_signature,
)
